services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      PORT: "3000"
    expose:
      - "3000"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
