import type { GeargraftCraft, GeargraftOperatorSettings } from '@/geargraft/data-access/geargraft-model'

import {
  catalysts,
  craftLabel,
  equipmentBases,
  findOption,
  materialFinishes,
  palettes,
  runeOrnaments,
  scoreCraft,
} from '@/geargraft/data-access/geargraft-model'
import { createGeargraftSvg, svgDataUri } from '@/geargraft/util/geargraft-svg'

export function createGeargraftMetadata(craft: GeargraftCraft, settings: GeargraftOperatorSettings, owner?: string) {
  const score = scoreCraft(craft, settings)
  const svg = createGeargraftSvg(craft, settings)

  return {
    attributes: [
      { trait_type: 'Equipment Base', value: findOption(equipmentBases, craft.base).label },
      { trait_type: 'Material Finish', value: findOption(materialFinishes, craft.finish).label },
      { trait_type: 'Rune Ornament', value: findOption(runeOrnaments, craft.rune).label },
      { trait_type: 'Catalyst', value: findOption(catalysts, craft.catalyst).label },
      { trait_type: 'Palette', value: findOption(palettes, craft.palette).label },
      { trait_type: 'Rarity', value: score.rarity },
      { trait_type: 'Stability', value: score.stability },
      { trait_type: 'Forge Risk', value: score.risk },
      { trait_type: 'Season', value: settings.season },
    ],
    description:
      'GearGraft playable equipment skin NFT generated by a wallet-signed Solana devnet MPL Core mint. Ownership verifies transferable game inventory and equipment/cosmetic permit status.',
    external_url: 'https://geargraft107.colmena.dev',
    image: svgDataUri(svg),
    name: craftLabel(craft),
    properties: {
      category: 'image',
      creators: owner ? [{ address: owner, share: 100 }] : [],
      files: [{ type: 'image/svg+xml', uri: svgDataUri(svg) }],
    },
    symbol: 'GEARG',
  }
}

export function metadataDataUri(metadata: unknown) {
  const json = JSON.stringify(metadata)
  const bytes = new TextEncoder().encode(json)
  let binary = ''

  for (const byte of bytes) {
    binary += String.fromCharCode(byte)
  }

  return `data:application/json;base64,${btoa(binary)}`
}
